### ISSUE TITLE
Error: `ETN_LoadImageBase64` - cannot identify image file `<_io.BytesIO object at 0xaddr>`

### ISSUE THREAD

**Issue by dbeecham** [olegchomp/TDComfyUI#11]
This error happens when you plug in a DAT into the `TDComfyUI` container without having pressed "re-init". At that point, `self.url` is not yet defined in the `load` method of `TdcomfyEXT`, which makes `datexec4` fail, and so no parameters are set up. When you then press the re-init pulse, none of the parameters are available in the Workflow parameter page. 

You can fix this by disconnecting the input and connecting it again, so that the datexec can trigger and set up all the parameters.

Maybe the `initialize` function of `TdcomfyEXT` should call something like `self.load()` at the end (if it can handle empty inputs), or the `__init__` should (conditionally?) define `self.url`.

**Comment by soundprayer** [comment]
It is giving me the same error BUT in my case reconnecting DAT doesn't work - still giving same error (tried with my own and with given TouchDesigner_img2img.json example).

**Comment by olegchomp** [comment]
Fixed in TDComfyUI-v.1.0.4
