### ISSUE TITLE
Error when connecting json

### ISSUE THREAD

**Issue by kubakubkub** [olegchomp/TDComfyUI#13]
I get this when connecting the json to the TDComfyUI,is there a solution for that?

![image](https://github.com/olegchomp/TDComfyUI/assets/156693141/d5400d47-095a-4e76-9689-ad23db1880ac)

**Comment by cold4ire** [comment]
anyone found a fix to this issue??

**Comment by olegchomp** [comment]
Fixed in TDComfyUI-v.1.0.4
