### ISSUE TITLE
No Workflow access on remote ComfyUI

### ISSUE THREAD

**Issue by Aleon3** [olegchomp/TDComfyUI#14]
I am able to create solid connection on remote machine and everything appears to be working except the interface on the workflow tab. So unable to connect null to image stream.

Is it possible to run ComfyUI on a remote PC and stream to local output yet?  (I made sure the .json file was loaded on the remote machine as well.)

**Comment by Freaknoizer** [comment]
> I am able to create solid connection on remote machine and everything appears to be working except the interface on the workflow tab. So unable to connect null to image stream.
> 
> Is it possible to run ComfyUI on a remote PC and stream to local output yet? (I made sure the .json file was loaded on the remote machine as well.)

Hi, im having same error...@Aleon3 did you solve this?

**Comment by olegchomp** [comment]
Fixed in TDComfyUI-v.1.0.4
