### ISSUE TITLE
TD+ComfyUI+Reactor(FaceSwap) = console_log_level - ERROR

### ISSUE THREAD

**Issue by 12368w** [olegchomp/TDComfyUI#15]
good time to you!
I identified the problem - What do you think about this?
I set up the connection between TouchDesigner and ComfyUI and everything works
but when I add the module - Reactor(FaceSwap) - the error appears:
got prompt
ERROR:root:Failed to validate prompt for output 10:
ERROR:root:* ReActorFaceSwap 13:
ERROR:root: - Value not in list: console_log_level: '1' not in [0, 1, 2]
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

I checked the code - the values ​​are set correctly

I think during the work the data format changes and an error appears

Here is part of the script code: -       "console_log_level": 1,

 "13": {
    "inputs": {
      "enabled": true,
      "swap_model": "inswapper_128.onnx",
      "facedetection": "retinaface_resnet50",
      "face_restore_model": "none",
      "face_restore_visibility": 1,
      "codeformer_weight": 0.5,
      "detect_gender_input": "no",
      "detect_gender_source": "no",
      "input_faces_index": "0",
      "source_faces_index": "0",
      "console_log_level": 1,
      "input_image": [
        "8",
        0
      ],
      "source_image": [
        "11",
        0
      ]
    },
    "class_type": "ReActorFaceSwap",
    "_meta": {
      "title": "ReActor - Fast Face Swap"
    }
  },

**Comment by 12368w** [comment]
перекопал плагин
проблему решил - можно закрывать

**Comment by olegchomp** [comment]
Fixed in TDComfyUI-v.1.0.4
