### ISSUE TITLE
[fix] code fix for TD-UI

### ISSUE THREAD

**Issue by maybites** [olegchomp/TDComfyUI#17]
Hi

Thank you very much for your tool. It works like a charm!

Here is a little fix we applied to make the generated UI inside TD match the ConfyUI node titles:

file TdcomfyEXT -> line 166

```					
class_title = comfyJson[node]['_meta']['title']
inputs = comfyJson[node]['inputs']
					
par_header = page.appendHeader(f'Header{node}',label=class_title,replace=True)
```

It grabs the node title and uses that instead of the node type - usefull especially if one has multiple of the same node type in the comfyUI patcher.

cheers

martin

**Comment by olegchomp** [comment]
Thank you!
Added in [TDComfyUI-v.1.0.7](https://github.com/olegchomp/TDComfyUI/releases/tag/v.1.0.7)
