### ISSUE TITLE
Request to Fix .tox File Issue with External ComfyUI Server

### ISSUE THREAD

**Issue by jaschahuisman** [olegchomp/TDComfyUI#18]
Issue Description:
When utilizing a server hosted on an external comfyui server via HTTPS or HTTP, the .tox file functionality encounters a setback due to the WebSocket node. The URL remains unstripped and receives a redundant prefix of "ws://", leading to instances like "ws://https://host.com/". This issue is considerably inconvenient. Could the domain stripping process be optimized to resolve this?

**Comment by mitchburk** [comment]
@jaschahuisman I am currently facing a similar issue when attempting to connect via a Runpod instance with an exposed 8188 port. I am able to connect to the instance, but the Workflow tab appears blank as if it can't connect back.

Any suggestions for where to look in the logs? I'm glad to make the necessary additions for having remote server as more of a first-priority function (that is my intended use case for this tool going forward).

Any help is greatly appreciated, glad to share my modified remote-friendly module version if I can find where to resolve it.

**Comment by RhizoNymph** [comment]
im having this issue with 1.0.6

**Comment by olegchomp** [comment]
Fixed in [TDComfyUI-v.1.0.7](https://github.com/olegchomp/TDComfyUI/releases/tag/v.1.0.7)
