### ISSUE TITLE
Remote connection from second machine

### ISSUE THREAD

**Issue by KOENTO** [olegchomp/TDComfyUI#2]
can't load "Workflow" from a remote machine (one with TD and one with Comfy). Firewall and everything checked, the API connects, I get feedback but I don't get "Workflow Ready". Works fine on the local machine.

(TD 2022.33910)

**Comment by olegchomp** [comment]
what you mean by
> can't load "Workflow" from a remote machine

Workflows is just .json files with description of ComfyUI nodes that parses with TD component

**Comment by KOENTO** [comment]
I'm sorry, I didn't express myself clearly
two scenarios:

first: Touchdesigner and ComfyUI on one machine
ComfyUI ip address: 127.0.0.1

Status: Initializing extension
Status: ComfyUI API connected
Status: Loading workflow
Status: Workflow destroyed
Status: Workflow ready

second: Touch designer on PC1 ComfyUI on PC2
TD ip address: 192.168.1.100
ComfyUI ip address: 192.168.1.101

Status: Initializing extension
Status: ComfyUI API connected
Status: Loading workflow
Status: Workflow destroyed
(stops here)

**Comment by olegchomp** [comment]
Will be fixed in new version (hope to release in few hours)

**Comment by olegchomp** [comment]
Fixed in v.1.0.1

**Comment by kirkon3** [comment]
What about if ComfyUI is hosted on Run.pod or external tools for GPU power? The IP address doesnt work...
