### ISSUE TITLE
two image outputs?

### ISSUE THREAD

**Issue by burritotrex** [olegchomp/TDComfyUI#20]
The "Send Image to Websocket" can't send an Alpha, so I am struggling to get a seperate mask to TD without applying it directly to the image. Any tipps on how to achieve it?

**Comment by olegchomp** [comment]
In ComfyUI you can convert mask to image, layout this images and send over websocket. In TouchDesigner crop this images in two.

**Comment by burritotrex** [comment]
ah, yep - that works! Thanks!!!!
