### ISSUE TITLE
The seed is not random. I think it is very troublesome to adjust the seed value manually. I hope to add this window to choose whether the seed value is random or fixed.

### ISSUE THREAD

**Issue by ZRZ-DEL** [olegchomp/TDComfyUI#24]
The seed is not random. I think it is very troublesome to adjust the seed value manually. I hope to add this window to choose whether the seed value is random or fixed.

**Comment by olegchomp** [comment]
Use expression "absTime.seconds"

**Comment by ZRZ-DEL** [comment]
> 使用表达式`absTime.seconds`
> 
> https://derivative.ca/UserGuide/AbsTime_Class
OK, thanks
