### ISSUE TITLE
ETN_LoadImageBase64

### ISSUE THREAD

**Issue by Tayshin-PV** [olegchomp/TDComfyUI#3]
Error occurred when executing ETN_LoadImageBase64
Решено в TouchDesigner -  TDComfyUI - settings - connection - Pulse. Статус стал Connected. и там же Workflow - Pulse. Начиная с версии 1.0.1 этот трюк не проходит, нет кнопки Workflow - Pulse

**Comment by olegchomp** [comment]
Workflow - open/destroy больше не нужен, параметры удаляются и создаются, при подключении файла из ComfyUI
