### ISSUE TITLE
Error when loading ETN LoadImageBase64

### ISSUE THREAD

**Issue by REDDKOMET** [olegchomp/TDComfyUI#7]
![image](https://github.com/olegchomp/TDComfyUI/assets/110946549/778991ca-cd14-48b0-b3aa-0074de96e8d6)

**Comment by olegchomp** [comment]
You need to reference TOP operator for img2img pipeline.

![image](https://github.com/olegchomp/TDComfyUI/assets/11017531/f180f4cc-78a5-4ed0-833f-0dfd18fd4aa8)
