### ISSUE TITLE
Broken Workflow Error on TD2023

### ISSUE THREAD

**Issue by 01timemachine** [olegchomp/TDComfyUI#8]
i installed TD new version and there is a problem with using ComfyUI json file. when i connect it to TDComfyUI it says: "Broken workflow" and "workflow destruction". is there anything i can do about it?

**Comment by olegchomp** [comment]
Latest TD version have [issues](https://forum.derivative.ca/t/tdresources-webclient-keyerror/398491/). For now only way is to use previous versions. (for ex. 2022.32660)

**Comment by 01timemachine** [comment]
hope it gets fixed soon. thanks for your effort!

**Comment by EranioCarbon** [comment]
Hello. 
I have an issue. The comfyUI is connected but the prompt is caching. Does anyone know a fix?
<img width="718" alt="image" src="https://github.com/olegchomp/TDComfyUI/assets/150896041/f96f30a6-ad23-44e1-b337-1f28b85c15a8">

**Comment by olegchomp** [comment]
@EranioCarbon what’s your TD version? 
Hover mouse on red label to show full error.

**Comment by EranioCarbon** [comment]
Hi. Thank you for responding. 
TD version is 
<img width="396" alt="image" src="https://github.com/olegchomp/TDComfyUI/assets/150896041/89a2963e-6167-420c-899b-79b1339cd400">
<img width="1237" alt="image" src="https://github.com/olegchomp/TDComfyUI/assets/150896041/aa2031bb-e786-4aae-bf9d-3f0923de77db">

**Comment by olegchomp** [comment]
> Hi. Thank you for responding. TD version is <img alt="image" width="396" src="https://private-user-images.githubusercontent.com/150896041/291126891-89a2963e-6167-420c-899b-79b1339cd400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTc3NTYsIm5iZiI6MTcwMjkxNzQ1NiwicGF0aCI6Ii8xNTA4OTYwNDEvMjkxMTI2ODkxLTg5YTI5NjNlLTYxNjctNDIwYy04OTliLTc5YjEzMzljZDQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxNjM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWRmMTNlNGZiNWJiYWY5ZTIwMzRmNDc2MDBhOTE3YTQzMjkzZjBkNDQzY2IyMGIzY2E0NGYyNGUxZTJmYTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xnlGivicwZ2MrsgiLg6sEFhpGb5m1xvE9i313T3sbNk"> <img alt="image" width="1237" src="https://private-user-images.githubusercontent.com/150896041/291126925-aa2031bb-e786-4aae-bf9d-3f0923de77db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTc3NTYsIm5iZiI6MTcwMjkxNzQ1NiwicGF0aCI6Ii8xNTA4OTYwNDEvMjkxMTI2OTI1LWFhMjAzMWJiLWU3ODYtNGFhZS1iZjlkLTNmMDkyM2RlNzdkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxNjM3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWVjYmNkNzI0YWUwOTllMTI2M2I0YzY2OTE3MTJmOWQ2NThmMGYzY2NiODBhZmVjYjAxMjVkNWJjMDQzMDcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v0jLpcO0S7DqyFESrCYFKJ2Is5vhaMQiXNVjdSzM0tY">

Re-Init connection on Settings tab

**Comment by olegchomp** [comment]
@EranioCarbon Re-Init connection on Settings tab

**Comment by gu-ma** [comment]
Hey, looks like line 16 in `TdcomfyEXT` should be uncommented (v1.0.3) 

<img width="429" alt="image" src="https://github.com/olegchomp/TDComfyUI/assets/4388440/02f6569f-6536-40c1-b6ae-ebe1fa529952">

**Comment by olegchomp** [comment]
@gu-ma i removed it to manual 'Re-init'. Otherwise it will initialize on every project save.

**Comment by olegchomp** [comment]
Fixed in TDComfyUI-v.1.0.4
